"""
Real, original pun content for a first batch of P1 topic pages.
Keyed by slug. Any P1 (or other) post not present here gets the
<!-- TODO: puns content --> placeholder from generate_wxr.py.

Each entry's lists are the body of one H2 section, in H2 Template sheet
order. Counts are 10-12 strong lines per section rather than forcing to
15-20 with filler — see SETUP.md for the plan to top these up before the
"[N]+" H1 counts are finalized.
"""

CONTENT = {

    "cat-puns": {
        "intro": "Cat puns turn feline moves, meows and cat-titudes into quick wordplay. Use them for Instagram captions, cards, and any moment your cat decides to be purr-fectly extra.",
        "one_liners": [
            "I'm not kitten around, that cat is hilarious.",
            "She's the cat's whiskers, and she knows it.",
            "My cat isn't lazy, she's just saving her nine lives.",
            "That joke was so bad it should be de-clawed.",
            "He's a purr-fessional napper.",
            "Cats don't do mornings; they do fur-naps.",
            "My cat's favorite subject in school was hiss-tory.",
            "She's claw-some, but don't tell her twice.",
            "That cat has some serious cat-titude.",
            "My cat's a copy-cat, literally — she's a clone.",
            "He only answers to treats, never to reason.",
            "That cat video was paw-sitively viral.",
        ],
        "short": [
            "Fur real.",
            "Cat-tastic.",
            "Meow or never.",
            "Purr-fectly fine.",
            "Claw-some day.",
            "Feline fine.",
            "Cat got jokes.",
            "Whisker business.",
            "Paws and reflect.",
            "Hiss-terical.",
            "Cattitude check.",
        ],
        "funny": [
            "My cat ignores me 23 hours a day, and judges me the 24th.",
            "I asked my cat for advice. She knocked a cup off the table instead.",
            "Cats have nine lives because one isn't enough time to ignore us properly.",
            "My cat's resume: professional sunbather, part-time furniture destroyer.",
            "A cat's love language is sitting on the one paper you need.",
            "My cat treats 3am like it's the most important meeting of her life.",
            "Cats don't fetch because they already know you'll bring it back yourself.",
            "My cat's favorite toy is always the box, never the toy inside it.",
            "A cat staring at a wall is just checking its investment portfolio.",
            "My cat's purr sounds supportive until you realize she's plotting.",
        ],
        "cute": [
            "Every slow blink from my cat feels like a tiny hug.",
            "My cat kneads the blanket like she's baking the softest bread.",
            "A cat curled into a comma is the coziest punctuation mark.",
            "Her tiny paw taps are how she says good morning.",
            "My cat follows me room to room, just to supervise snacks.",
            "A sleepy cat chirp is the sweetest sound in the house.",
            "She tucks her paws in and becomes a little loaf of love.",
            "My cat headbutts me when words aren't enough.",
            "Her whiskers twitch in her sleep, chasing dream mice.",
            "A cat's tail curled around your arm is a quiet 'stay close.'",
        ],
        "captions": [
            "Feline fine today.",
            "Living my nine lives.",
            "Purr-fectly content.",
            "Cat-titude on display.",
            "Meow's the moment.",
            "Whisker away from perfect.",
            "Sun, naps, repeat.",
            "Claw-some vibes only.",
            "Paws for a photo.",
            "Fur baby, best baby.",
        ],
        "kids": [
            "Q: What do you call a cat that loves to bowl? A: An alley cat!",
            "Q: Why was the cat sitting on the computer? A: To keep an eye on the mouse!",
            "Q: What's a cat's favorite color? A: Purr-ple!",
            "Q: What do cats eat for breakfast? A: Mice Krispies!",
            "Q: Why are cats bad storytellers? A: They only have one tail!",
            "Q: What do you call a cat who loves to play cards? A: A cheetah!",
            "Q: What's a cat's favorite TV show? A: Claw and Order!",
            "Q: How does a cat say thank you? A: With a purr-sonal note!",
            "Q: What do you call a pile of kittens? A: A meow-ntain!",
            "Q: Why did the cat join the band? A: Because it had the right mewsic skills!",
        ],
        "love": [
            "You're the cat's meow, and I'm not just saying that to get treats.",
            "My heart does a slow blink every time I see you.",
            "You had me at 'here, kitty' — now I'm yours for nine lives.",
            "Loving you is easy; it's purr-fectly natural.",
            "You're the only lap I actually want to curl up in.",
            "You make my whiskers twitch in the best way.",
            "I'd trade all nine lives just to spend one with you.",
            "You're the cream to my saucer.",
            "Every day with you feels like a sunny windowsill nap.",
            "You're claw-ways on my mind.",
        ],
        "birthday": [
            "Happy birthday to someone who's the cat's meow every single year.",
            "Hope your birthday is purr-fect from morning nap to midnight snack.",
            "Another year older, still claw-some as ever. Happy birthday!",
            "May your birthday be filled with treats and zero hairballs.",
            "You're not getting older, you're just leveling up your nine lives.",
            "Happy birthday — go celebrate like a cat who found the sunny spot.",
            "Here's to a birthday as cozy as a cat in a laundry basket.",
            "Happy birthday to a true purr-sonality.",
        ],
        "pickup_lines": [
            "Are you a cat? Because I'm feline a connection.",
            "Is your name Whiskers? Because you're making my heart twitch.",
            "I must be a cat toy, because I can't stop chasing you.",
            "Are you catnip? Because I can't stay away.",
            "Did you just purr, or did my heart skip a beat?",
            "I'd use eight of my lives just for a shot with you.",
            "You must be a laser pointer, because I can't look away.",
            "Are you a sunbeam? Because I want to curl up right there with you.",
        ],
        "jokes": [
            "Q: Why did the cat sit on the newspaper? A: It wanted to keep up with current events.",
            "Q: What do you call a cat that works for the Red Cross? A: A first-aid kit!",
            "Q: Why don't cats play poker in the jungle? A: Too many cheetahs!",
            "Q: What did the cat say when it lost all its toys? A: 'That's how the mouse bounces.'",
            "Q: What's a cat's favorite dessert? A: Mice cream!",
            "Q: Why did the cat go to art school? A: To learn how to draw-paw-ings!",
            "Q: What do you call a cat that gets everything it wants? A: Purr-suasive.",
            "Q: Why was the cat afraid of the tree? A: Because of its bark!",
        ],
        "how_to_use": "Cat puns work anywhere a cat shows up: birthday cards for cat owners, party signs for a cat-themed get-together, classroom jokes for animal units, or a quick caption the second your cat does something camera-worthy.",
        "faqs": [
            {
                "q": "What are the best cat puns?",
                "a": "The best cat puns lean on real cat behavior — kneading, meowing, napping and hunting — rather than generic animal jokes. Lines like 'purr-fectly fine' and 'claw-some' work because they sound like natural cat words. The strongest ones double as both a joke and a caption.",
            },
            {
                "q": "Are cat puns good for kids?",
                "a": "Yes, cat puns are a great fit for kids because they're clean, visual and easy to picture. Simple setups like 'what's a cat's favorite color' teach wordplay without any content a parent or teacher would need to screen first.",
            },
            {
                "q": "How do you make a cat pun?",
                "a": "Start with a cat-specific word — meow, purr, claw, whisker, feline — and listen for a word it sounds like or rhymes with, such as 'purr-fect' from 'perfect.' See our guide on how to write a pun for the full step-by-step method.",
            },
        ],
        "bridge_links": [
            {"label": "Dog Puns", "slug": "dog-puns"},
            {"label": "Rabbit Puns", "slug": "rabbit-puns"},
            {"label": "Pet Puns", "slug": "pet-puns"},
        ],
    },

    "dog-puns": {
        "intro": "Dog puns turn tail wags, fetch and puppy energy into quick wordplay. Use them for captions, cards, or any moment your dog is being paw-sitively ridiculous.",
        "one_liners": [
            "He's not misbehaving, he's just a little ruff around the edges.",
            "That dog has some serious collar-ful personality.",
            "She's not spoiled, she's just well-leashed.",
            "My dog isn't lazy, he's just conserving fetch energy.",
            "That trick was paw-sitively impressive.",
            "He's a good boy, and he knows it.",
            "She's the leader of the pack, literally and figuratively.",
            "My dog's bark is worse than his bite, and both are loud.",
            "That dog has more hype than a stadium crowd.",
            "He's not barking at nothing, he's barking at everything.",
            "She's a tail-wagging bundle of chaos.",
            "My dog treats every delivery driver like a wanted criminal.",
        ],
        "short": [
            "Paw-some.",
            "Ruff day.",
            "Fetch life.",
            "Woof and tumble.",
            "Collar me impressed.",
            "Bark to basics.",
            "Pup-tastic.",
            "Leash of my worries.",
            "Tail wags only.",
            "Howl's it going.",
        ],
        "funny": [
            "My dog barks at the vacuum like it owes him money.",
            "A dog's zoomies are just unpaid energy bills, suddenly due.",
            "My dog thinks the mailman is a recurring villain in his life story.",
            "A dog's guilty face is basically a signed confession.",
            "My dog's idea of guarding the house is barking at his own reflection.",
            "A dog chasing its tail is just running late for itself.",
            "My dog's dinner bark could wake up three zip codes.",
            "A dog's nose always finds the one thing you dropped a week ago.",
            "My dog treats every walk like it's the first walk in recorded history.",
            "A dog's 'I'm fine' face always comes right after eating a sock.",
        ],
        "cute": [
            "His tail thumps the floor every time I walk in the room.",
            "A sleepy puppy sigh is the softest sound in the house.",
            "My dog tilts his head like every word I say is fascinating.",
            "His paws twitch in his sleep, chasing dream squirrels.",
            "A dog leaning its whole weight into you is pure trust.",
            "My dog waits by the door just to greet me like I'm royalty.",
            "His little snore is the best lullaby I never asked for.",
            "A puppy's first zoomie of the day is basically joy on legs.",
            "My dog tucks his nose under his paw when the room gets quiet.",
            "His whole body wags when he sees the leash.",
        ],
        "captions": [
            "Paw-sitively happy.",
            "Living the leash life.",
            "Tail wags and sunny days.",
            "Fetch mode: on.",
            "Good boy energy only.",
            "Woof life, best life.",
            "Pup-tastic afternoon.",
            "Collar-ing all the attention.",
            "Zoomies included.",
            "Ruff and ready.",
        ],
        "kids": [
            "Q: What kind of dog loves to take bubble baths? A: A shampoo-dle!",
            "Q: What do you call a cold dog? A: A chili dog!",
            "Q: Why did the dog cross the road twice? A: To fetch a boomerang!",
            "Q: What's a dog's favorite instrument? A: The trum-bone!",
            "Q: What do you call a dog that does magic tricks? A: A labracadabrador!",
            "Q: Why do dogs make terrible dancers? A: They have two left feet!",
            "Q: What kind of dog tells time? A: A watch dog!",
            "Q: What do you call a dog that works at a bakery? A: A pup-cake!",
            "Q: Why did the dog sit in the shade? A: It didn't want to be a hot dog!",
            "Q: What's a puppy's favorite kind of story? A: A tail of adventure!",
        ],
        "love": [
            "You had me at 'good boy,' and I've been yours ever since.",
            "You're the best part of my whole walk, every single day.",
            "My heart wags every time you walk into the room.",
            "You're the human version of coming home to a happy tail.",
            "I'd fetch the moon for you, no leash required.",
            "You're paw-sitively the one.",
            "Loving you feels as easy as a belly rub.",
            "You're my favorite person to zoom around with.",
            "Every day with you feels like the first walk of spring.",
            "You've got me sit, stay, and smiling.",
        ],
        "birthday": [
            "Happy birthday to someone with good-boy energy all year round.",
            "Hope your birthday is full of treats and zero vacuum battles.",
            "Another year older, still the goodest of good boys. Happy birthday!",
            "May your birthday have more zoomies than quiet moments.",
            "Happy birthday — go chase something fun today.",
            "Here's to a birthday as joyful as a tail-wagging welcome home.",
            "Happy birthday to a true pack leader.",
            "Hope today brings you all the belly rubs you deserve.",
        ],
        "pickup_lines": [
            "Are you a leash? Because I feel attached to you already.",
            "Is your name Fido? Because I'm feeling loyal already.",
            "I must be a tennis ball, because I can't stop chasing you.",
            "Did you just whistle, or did my heart just come running?",
            "Are you a belly rub? Because you're making my whole body happy.",
            "I'd skip a walk just to sit here and talk to you.",
            "You must be a squeaky toy, because I can't stop noticing you.",
            "Are you a treat? Because I'd sit, stay, and roll over for you.",
        ],
        "jokes": [
            "Q: Why did the dog go to the bank? A: To check his bark account!",
            "Q: What do you call a dog magician? A: A labracadabrador!",
            "Q: Why was the dog confused? A: Because he was a collie and couldn't make up his mind!",
            "Q: What do you get when you cross a dog with a calculator? A: A friend you can count on!",
            "Q: Why did the dog sit on the computer? A: To keep an eye on the mouse, same as the cat!",
            "Q: What's a dog's favorite pizza topping? A: Pupperoni!",
            "Q: Why do dogs run in circles? A: It's hard to run in squares!",
            "Q: What do you call a dog that's always on time? A: A punc-tu-ale!",
        ],
        "how_to_use": "Dog puns fit birthday cards for dog lovers, party signs for a pup-themed gathering, classroom jokes for animal units, or a caption the second your dog does something zoomie-worthy.",
        "faqs": [
            {
                "q": "What are the best dog puns?",
                "a": "The best dog puns use real dog behavior — fetch, zoomies, tail wags and barking — instead of generic animal jokes. Lines like 'paw-sitively happy' and 'ruff day' land because they sound like things a dog would actually say. The strongest double as both a joke and a caption.",
            },
            {
                "q": "Are dog puns good for kids?",
                "a": "Yes, dog puns are great for kids because they're clean, visual and build on animal sounds and behavior kids already know. Simple Q&A setups like the shampoo-doodle joke teach wordplay without needing any content review.",
            },
            {
                "q": "How do you make a dog pun?",
                "a": "Start with a dog-specific word — bark, fetch, paw, leash, woof — and find a similar-sounding word, like 'pupperoni' from 'pepperoni.' Our guide on how to write a pun walks through the full method step by step.",
            },
        ],
        "bridge_links": [
            {"label": "Cat Puns", "slug": "cat-puns"},
            {"label": "Rabbit Puns", "slug": "rabbit-puns"},
            {"label": "Pet Puns", "slug": "pet-puns"},
        ],
    },

    "pizza-puns": {
        "intro": "Pizza puns turn toppings, crust and cheese pulls into quick wordplay. Use them for captions, party invites, or any time pizza night deserves a one-liner.",
        "one_liners": [
            "That pizza place really knows how to roll with the punches.",
            "This pizza is a slice above the rest.",
            "We're mozzarella the way to pizza perfection.",
            "That topping choice was a bold pizza move.",
            "She's the dough of my eye.",
            "This crust is crust-worthy of a standing ovation.",
            "That pizza party got saucy fast.",
            "He's really stepping up his pizza game.",
            "This pie is on a roll tonight.",
            "That pizza joke really knead-ed work, but it landed.",
            "We're having a grate time with this cheese pull.",
            "This slice is pizza-tively perfect.",
        ],
        "short": [
            "Pizza my heart.",
            "Crust life.",
            "Saucy and proud.",
            "Cheese, please.",
            "Slice, slice baby.",
            "Dough it again.",
            "Pie-oneer status.",
            "Topping tier.",
            "Extra cheesy.",
            "Pizza o'clock.",
        ],
        "funny": [
            "I have a great pizza joke, but it's a little too cheesy.",
            "My diet started today, right after this pizza ends.",
            "Pizza doesn't ask questions, pizza understands.",
            "My relationship status: committed to pizza.",
            "A pizza's favorite exercise is the extra slice curl.",
            "I'm not saying pizza solves everything, but it's never made things worse.",
            "My pizza order is basically a love letter to cheese.",
            "A pizza box is just a very honest diary of my evening.",
            "I told the pizza place my order was 'no notes.' They understood.",
            "My pizza and I have been through a lot, mostly delivery delays.",
        ],
        "cute": [
            "Sharing the last slice is basically a love language.",
            "A warm pizza box smell is instant comfort.",
            "Watching the cheese stretch on the first bite never gets old.",
            "A pizza night in is the coziest kind of plan.",
            "The smell of fresh basil on a pizza feels like a hug.",
            "Picking toppings together is a tiny act of teamwork.",
            "A heart-shaped pepperoni placement is secretly the sweetest gesture.",
            "There's nothing cozier than a pizza box and a good movie.",
            "The first cheesy pull of the night deserves its own photo.",
            "Saving someone the crust-free middle slice is true love.",
        ],
        "captions": [
            "Pizza my heart.",
            "Living the crust life.",
            "Extra cheese, extra happy.",
            "Slice of the good life.",
            "Saucy and satisfied.",
            "Dough, oh my.",
            "Topping off the night.",
            "Pie in the sky mood.",
            "Cheese pull champion.",
            "Pizza o'clock, always.",
        ],
        "kids": [
            "Q: What do you call a pizza that can play basketball? A: A deep-dish dunk!",
            "Q: Why did the pizza maker go broke? A: He kept giving people too much dough!",
            "Q: What's a pizza's favorite type of music? A: Anything with a good beet!",
            "Q: Why did the pizza slice stop halfway? A: It ran out of steam!",
            "Q: What do you call a pizza that tells jokes? A: A comedi-pie!",
            "Q: Why did the cheese go to the party alone? A: It wanted to stand a-grate!",
            "Q: What's a pizza's favorite game? A: Topping tag!",
            "Q: Why was the pizza so confident? A: It had a lot of self a-steam!",
            "Q: What do you call a shy slice of pizza? A: Shy-oni!",
            "Q: Why did the pizza go to school? A: To become a little smarter-ella!",
        ],
        "love": [
            "You're the pepperoni to my pizza.",
            "I love you a whole pie's worth, no slices held back.",
            "You had me at extra cheese, and I never looked back.",
            "You're the topping that makes everything better.",
            "Falling for you was as easy as the first cheesy bite.",
            "You're my favorite delivery of the week, every week.",
            "I'd share my last slice with you, and that's saying something.",
            "You're the crust that holds my whole world together.",
            "Every date with you feels like a pizza night in.",
            "You're basically my favorite topping combo: rare and perfect.",
        ],
        "birthday": [
            "Happy birthday to someone who's the slice of the party.",
            "Hope your birthday has extra cheese and zero burnt crusts.",
            "Another year older, still the main topping in everyone's life. Happy birthday!",
            "May your birthday be as satisfying as the first bite of a fresh pie.",
            "Happy birthday — go order the toppings you actually want this time.",
            "Here's to a birthday stacked higher than a deep-dish.",
            "Happy birthday to someone who's truly a-grate.",
            "Hope today is topped with everything good.",
        ],
        "pickup_lines": [
            "Are you a pizza? Because you're making my heart melt like cheese.",
            "Is your name Margherita? Because you're a classic I can't resist.",
            "I must be dough, because I'm rising every time I see you.",
            "Are you extra cheese? Because you make everything better.",
            "Did you just order a pizza, or did my heart skip a slice?",
            "I'd wait 45 minutes for delivery just to see you at the door.",
            "You must be a pizza oven, because things are heating up.",
            "Are you a topping? Because I'd pick you every single time.",
        ],
        "jokes": [
            "Q: What did the pizza say to the oven? A: 'This relationship is getting too hot!'",
            "Q: Why did the pizza maker quit his job? A: He couldn't make enough dough!",
            "Q: What do you call a pizza that's always on time? A: Punc-tu-al-ian!",
            "Q: Why do pizzas make bad comedians? A: Their jokes are too cheesy!",
            "Q: What's a pizza's favorite holiday? A: Pi Day, obviously!",
            "Q: Why was the pizza embarrassed? A: It saw the salad dressing!",
            "Q: What do you call a pizza that studies hard? A: A smart-a-roni!",
            "Q: Why did the pizza slice break up with the fork? A: It needed its own space!",
        ],
        "how_to_use": "Pizza puns are perfect for pizza-party invites, menu boards, birthday cards for pizza lovers, or a caption the second the cheese pull happens on camera.",
        "faqs": [
            {
                "q": "What are the best pizza puns?",
                "a": "The best pizza puns use real pizza words — dough, crust, cheese, slice, toppings — instead of generic food jokes. Lines like 'pizza my heart' and 'a-grate' work because they sound like natural pizza vocabulary. The strongest double as both a joke and a caption.",
            },
            {
                "q": "Are pizza puns good for kids?",
                "a": "Yes, pizza puns are great for kids because pizza is a food they already know and love, which makes the wordplay easy to follow. Clean Q&A jokes like the 'comedi-pie' one are simple enough for classrooms and lunchboxes.",
            },
            {
                "q": "How do you make a pizza pun?",
                "a": "Start with a pizza word — dough, cheese, crust, slice, pepperoni — and listen for a similar-sounding word, like 'a-grate' from 'a great.' See our guide on how to write a pun for the full method.",
            },
        ],
        "bridge_links": [
            {"label": "Taco Puns", "slug": "taco-puns"},
            {"label": "Cheese Puns", "slug": "cheese-puns"},
            {"label": "Meal & Dish Puns", "slug": "meal-and-dish-puns"},
        ],
    },

    "coffee-puns": {
        "intro": "Coffee puns turn espresso, beans and morning rituals into quick wordplay. Use them for captions, mugs, or any moment coffee is the only thing keeping you upright.",
        "one_liners": [
            "I'm only a morning person after the first cup, no espresso-ptions.",
            "That barista really brewed up something special.",
            "She's the espresso of my affection.",
            "This roast is grounds for celebration.",
            "That coffee order was bean a while coming.",
            "He's always perc-ing up at the smell of fresh coffee.",
            "This latte art is brew-tiful.",
            "That meeting needed way more coffee and way less talking.",
            "She's a-latte fun before 9am.",
            "This coffee shop really has its roast together.",
            "That cold brew hit different today.",
            "He's the whole bean, not just the grounds.",
        ],
        "short": [
            "Brew-tiful day.",
            "Espresso yourself.",
            "Bean there, done that.",
            "Latte love.",
            "Grounds for joy.",
            "Perc up.",
            "Mug life.",
            "Roast and toast.",
            "Drip it like it's hot.",
            "Steamed and dreamy.",
        ],
        "funny": [
            "My blood type is coffee, with a side of more coffee.",
            "I don't need an alarm clock, I need a louder coffee maker.",
            "A decaf order in my house is grounds for an intervention.",
            "My coffee and I have a very committed, very caffeinated relationship.",
            "I told my coffee my secrets, it just steamed quietly in agreement.",
            "My productivity graph is just a coffee cup refilling itself.",
            "A coffee spill before 8am counts as a personal tragedy.",
            "My coffee order has more modifiers than my actual personality.",
            "I don't do mornings, I do large coffees that enable mornings.",
            "A good coffee mug deserves its own retirement plan.",
        ],
        "cute": [
            "The first sip of coffee in the morning feels like a warm hug.",
            "Sharing a coffee date is secretly one of the sweetest plans.",
            "The smell of coffee brewing is the coziest wake-up call.",
            "A heart drawn in latte foam is a tiny daily gift.",
            "Holding a warm mug on a cold morning is its own comfort.",
            "Two coffees ordered 'the usual' is a quiet kind of closeness.",
            "A slow coffee morning with someone you love is pure peace.",
            "The steam rising off a fresh cup feels like a tiny good-morning wave.",
            "Remembering someone's coffee order by heart is its own love language.",
            "A coffee shared on the porch is the softest start to a day.",
        ],
        "captions": [
            "Brew-tiful morning.",
            "Espresso yourself today.",
            "Latte love, always.",
            "Bean there, loved that.",
            "Grounds for a good day.",
            "Steamed, not stirred.",
            "Mug life chosen.",
            "Perc-ing up right now.",
            "Drip drip, happy trip.",
            "Roasted to perfection.",
        ],
        "kids": [
            "Q: Why did the coffee file a police report? A: It got mugged!",
            "Q: What do you call a sad cup of coffee? A: De-pressed-o!",
            "Q: Why did the coffee bean go to school? A: To get ground-ed in the basics!",
            "Q: What's a coffee cup's favorite game? A: Hide and brew!",
            "Q: Why was the coffee always invited to parties? A: It perked everyone up!",
            "Q: What do you call coffee that's always on time? A: Punc-tu-al-attè!",
            "Q: Why did the coffee cup go to the doctor? A: It was feeling a little drained!",
            "Q: What's a coffee bean's favorite subject? A: Grounds-work!",
            "Q: Why did the mug blush? A: Because the coffee was too hot!",
            "Q: What do you call a coffee that tells jokes? A: A pun-dripper!",
        ],
        "love": [
            "You're the cream to my coffee.",
            "I'd choose you over my morning coffee, and that's saying a lot.",
            "You're the reason I perk up every single morning.",
            "Loving you feels as warm as the first sip of coffee.",
            "You're my favorite blend of sweet and strong.",
            "You had me at 'can I buy you a coffee,' and I never left.",
            "You're the espresso shot my whole day needed.",
            "I'm grounds-for-you kind of in love.",
            "You're the latte art on an otherwise plain morning.",
            "Every morning with you is brew-tiful.",
        ],
        "birthday": [
            "Happy birthday to someone who brews up joy wherever they go.",
            "Hope your birthday is strong, warm, and perfectly brewed.",
            "Another year older, still the espresso shot the world needed. Happy birthday!",
            "May your birthday have zero spills and all the refills.",
            "Happy birthday — go treat yourself to the fancy coffee order.",
            "Here's to a birthday as smooth as a good cold brew.",
            "Happy birthday to someone who's truly brew-tiful inside and out.",
            "Hope today is grounds for a great celebration.",
        ],
        "pickup_lines": [
            "Are you coffee? Because I can't start my day without you.",
            "Is your name Espresso? Because you just woke my heart up.",
            "I must be sugar, because I'm falling for you completely.",
            "Are you a latte? Because you've got my heart steaming.",
            "Did you just brew, or did my heart skip a bean?",
            "I'd wait in line for you longer than I wait for coffee.",
            "You must be a French press, because you're strong and I'm into it.",
            "Are you decaf? Because even then, I'd still be wired for you.",
        ],
        "jokes": [
            "Q: Why did the coffee cup go to therapy? A: It had too many grounds for concern!",
            "Q: What do you call a coffee that won't shut up? A: A loud-mouth latte!",
            "Q: Why did the barista break up with the customer? A: No chemistry, just caffeine!",
            "Q: What do you call a nervous coffee bean? A: A bit jittery!",
            "Q: Why did the coffee maker get a promotion? A: It really perked up the office!",
            "Q: What's a coffee's favorite dance? A: The perc-olator!",
            "Q: Why did the espresso machine win an award? A: Outstanding shot!",
            "Q: What do you call a coffee that studies philosophy? A: Deep roast!",
        ],
        "how_to_use": "Coffee puns fit mug designs, café chalkboards, birthday cards for coffee lovers, or a quick caption the moment your latte art turns out better than expected.",
        "faqs": [
            {
                "q": "What are the best coffee puns?",
                "a": "The best coffee puns use real coffee words — espresso, brew, grounds, roast, latte — rather than generic drink jokes. Lines like 'espresso yourself' and 'brew-tiful' work because they sound like things a coffee shop would actually print. The strongest ones double as both a joke and a caption.",
            },
            {
                "q": "Are coffee puns good for kids?",
                "a": "Yes, coffee puns are good for kids in a classroom or card-making context, since the wordplay itself is clean — the jokes work even for kids who've never had a cup, as long as an adult is nearby for any actual coffee talk.",
            },
            {
                "q": "How do you make a coffee pun?",
                "a": "Start with a coffee-specific word — brew, bean, roast, grounds, espresso — and find a similar-sounding phrase, like 'espresso yourself' from 'express yourself.' Our guide on how to write a pun covers the full step-by-step method.",
            },
        ],
        "bridge_links": [
            {"label": "Tea Puns", "slug": "tea-puns"},
            {"label": "Drink Puns", "slug": "drink-puns"},
            {"label": "Dad Joke Puns", "slug": "dad-joke-puns"},
        ],
    },

    "christmas-puns": {
        "intro": "Christmas puns turn Santa, snow and stockings into quick wordplay. Use them for cards, captions, or any moment the holidays deserve a little extra cheer.",
        "one_liners": [
            "That gift wrap job was snow joke.",
            "She's got the Christmas spirit elf-contained.",
            "This tree is really branching out this year.",
            "That ornament broke the ice at the party.",
            "He's sleighing the holiday decorations this year.",
            "This cookie batch is dough-lightful.",
            "That family photo was picture-perfect, naughty list and all.",
            "She's wrapped up in the holiday spirit, literally.",
            "This stocking stuffer game is on point.",
            "That snowman had a real cool personality.",
            "He's jingle all the way, every single day.",
            "This holiday playlist is un-wrap-able good.",
        ],
        "short": [
            "Snow joke.",
            "Sleigh all day.",
            "Elf-made magic.",
            "Tinsel town vibes.",
            "Merry and bright.",
            "Jingle mode on.",
            "Deck the halls.",
            "Cookie season.",
            "Wrapped with love.",
            "Holly jolly.",
        ],
        "funny": [
            "My Christmas budget and I are not currently speaking.",
            "I didn't choose the naughty list, the naughty list chose me.",
            "My holiday decorating style is best described as 'enthusiastic chaos.'",
            "Santa checks his list twice; I check my gift returns three times.",
            "My Christmas tree has more ornaments than structural integrity.",
            "A fruitcake's only job is to be regifted forever.",
            "My holiday playlist started in October and nobody can stop me.",
            "I told Santa I'd been good. He asked for receipts.",
            "My stocking stuffers are 90% chocolate, 10% regret.",
            "A tangled string of lights is basically a Christmas rite of passage.",
        ],
        "cute": [
            "The smell of fresh pine always feels like the start of something warm.",
            "A hot cocoa with extra marshmallows is a tiny act of self-care.",
            "Watching the first snow fall outside the window never gets old.",
            "A homemade ornament means more than any store-bought one.",
            "Wrapping a gift with someone you love is its own small holiday.",
            "The twinkle of tree lights in a dark room feels like quiet magic.",
            "A family recipe passed down each year is the sweetest tradition.",
            "Matching pajamas on Christmas morning is pure holiday softness.",
            "A handwritten card means more than anything wrapped in a bow.",
            "The first carol on the radio always sparks the same little smile.",
        ],
        "captions": [
            "Merry and bright.",
            "Sleighing the season.",
            "Snow joke, just joy.",
            "Tinsel and twinkle lights.",
            "Elf mode: activated.",
            "Jingle all the way.",
            "Holly jolly vibes.",
            "Deck the halls, deck the feed.",
            "Wrapped in holiday magic.",
            "Cookies, cocoa, cheer.",
        ],
        "kids": [
            "Q: What do you call Santa's helpers? A: Subordinate Clauses!",
            "Q: Why was the snowman looking through the carrots? A: He was picking his nose!",
            "Q: What do you get if you cross a Christmas tree with an apple? A: A pineapple!",
            "Q: What do elves learn in school? A: The elf-abet!",
            "Q: Why couldn't the Christmas tree stand up? A: It didn't have any legs, just a trunk!",
            "Q: What's Santa's favorite pizza topping? A: Jingle bell peppers!",
            "Q: Why did Rudolph get a bad report card? A: Because he went down in history!",
            "Q: What do you call a reindeer with no eyes? A: No eye deer!",
            "Q: What's the best Christmas present in the world? A: A broken drum, you just can't beat it!",
            "Q: Why was the snowman rummaging through the bag of carrots? A: He wanted to pick his nose!",
        ],
        "love": [
            "You're the star on top of my Christmas tree.",
            "All I want for Christmas is you, decorations are just a bonus.",
            "You wrapped yourself around my heart like the best kind of tinsel.",
            "Every holiday feels merrier with you under the mistletoe.",
            "You're the gift I look forward to every single year.",
            "Loving you feels as warm as a fire on Christmas Eve.",
            "You're my favorite tradition, hands down.",
            "You make every Christmas morning feel like the best one yet.",
            "You're the cocoa to my marshmallow.",
            "I'd pick you under the mistletoe every single time.",
        ],
        "birthday": [
            "Happy birthday to someone who makes every season feel like the holidays.",
            "Hope your birthday is as bright as a fully lit Christmas tree.",
            "Another year older, still the best gift this family ever got. Happy birthday!",
            "May your birthday be merry, bright, and extremely well-fed.",
            "Happy birthday — go unwrap something good today.",
            "Here's to a birthday as cozy as Christmas morning.",
            "Happy birthday to a true holly jolly legend.",
            "Hope today is wrapped in all your favorite things.",
        ],
        "pickup_lines": [
            "Are you Christmas morning? Because my heart is racing already.",
            "Is your name Holly? Because you're the best part of December.",
            "I must be a stocking, because I've got room for you in my life.",
            "Are you mistletoe? Because I can't resist standing near you.",
            "Did you just light up, or did my heart just get brighter?",
            "I'd skip wrapping paper just to unwrap time with you.",
            "You must be a snow globe, because my world just got shaken up.",
            "Are you a Christmas gift? Because I've been waiting all year for you.",
        ],
        "jokes": [
            "Q: What do you call a broke Santa? A: Saint Nickel-less!",
            "Q: Why does Santa have three gardens? A: So he can ho-ho-ho!",
            "Q: What do you call a cat on the beach at Christmas time? A: Sandy Claws!",
            "Q: Why did the gingerbread man go to the doctor? A: He was feeling crummy!",
            "Q: What do you sing at a snowman's birthday party? A: 'Freeze a jolly good fellow!'",
            "Q: What's the difference between Christmas and your job? A: At Christmas you get fired with enthusiasm!",
            "Q: Why was Santa's little helper depressed? A: He had low elf-esteem!",
            "Q: What do you call Santa when he stops moving? A: Santa Pause!",
        ],
        "how_to_use": "Christmas puns fit holiday cards, gift tags, party signs, classroom worksheets, and captions for every tree, cocoa and ugly-sweater photo of the season.",
        "faqs": [
            {
                "q": "What are the best Christmas puns?",
                "a": "The best Christmas puns use real holiday words — Santa, sleigh, elf, tinsel, mistletoe — instead of generic winter jokes. Lines like 'snow joke' and 'holly jolly vibes' land because they sound like real holiday phrases. The strongest ones double as both a joke and a card message.",
            },
            {
                "q": "Are Christmas puns good for kids?",
                "a": "Yes, Christmas puns are great for kids because the holiday itself is already full of characters and imagery kids know well — Santa, reindeer, snowmen — which makes the wordplay easy to follow in a classroom or at home.",
            },
            {
                "q": "How do you make a Christmas pun?",
                "a": "Start with a holiday word — sleigh, elf, snow, tinsel, stocking — and find a similar-sounding phrase, like 'snow joke' from 'no joke.' See our guide on how to write a pun for the full step-by-step method.",
            },
        ],
        "bridge_links": [
            {"label": "Halloween Puns", "slug": "halloween-puns"},
            {"label": "Thanksgiving Puns", "slug": "thanksgiving-puns"},
            {"label": "Seasonal Holiday Puns", "slug": "seasonal-holiday-puns"},
        ],
    },

    "birthday-puns": {
        "intro": "Birthday puns turn cake, candles and getting older into quick wordplay. Use them for cards, captions, or any birthday that needs a little extra icing on top.",
        "one_liners": [
            "Another year older, and still the icing on everyone's cake.",
            "That birthday cake really took the cake tonight.",
            "She's aging like fine wine, or at least fine cake.",
            "This candle count is getting a little toasty.",
            "He's really leveling up his birthday game this year.",
            "That party really brought the cake-citement.",
            "She's not getting older, she's getting more frosted.",
            "This birthday wish list is sweet, literally.",
            "He blew out the candles like a true pro.",
            "That cake topper really stole the spotlight.",
            "She's the whole party, candles and all.",
            "This birthday banner is hanging on for dear life, like all of us.",
        ],
        "short": [
            "Cake mode on.",
            "Candle power.",
            "Age is just icing.",
            "Party of one, plus cake.",
            "Sprinkle season.",
            "Wish granted.",
            "Frosted and fabulous.",
            "Balloon o'clock.",
            "Confetti ready.",
            "Cheers to years.",
        ],
        "funny": [
            "I'm not aging, I'm just adding more candle-related fire hazards.",
            "My birthday wish is always the same: for someone else to do the dishes.",
            "Another year older, same amount of cake-related poor decisions.",
            "I blow out candles like I'm putting out a tiny, delicious fire.",
            "My birthday cake and I have an understanding: all of it is mine.",
            "I don't need a party, I need cake and zero responsibilities for one day.",
            "A birthday is just an annual excuse to eat cake for breakfast.",
            "My age is a secret, but my cake order is not.",
            "I'm convinced birthday candles get harder to blow out every single year.",
            "My birthday plans: cake, nap, more cake.",
        ],
        "cute": [
            "A handwritten birthday card still beats any store receipt gift.",
            "The quiet moment before blowing out candles feels like pure hope.",
            "A surprise birthday balloon tied to the door is instant joy.",
            "Someone remembering your exact cake flavor is its own love language.",
            "A birthday morning text from someone far away still feels close.",
            "The first bite of birthday cake always tastes a little sweeter.",
            "A home-decorated cake, wobbly frosting and all, means more than perfect.",
            "Blowing out candles with someone you love watching is a tiny forever moment.",
            "A birthday playlist made just for you is a quiet kind of gift.",
            "The smell of cake baking is basically the smell of celebration.",
        ],
        "captions": [
            "Cake mode: activated.",
            "Another trip around the sun.",
            "Sprinkles and celebration.",
            "Candle power, fully charged.",
            "Confetti and cake, please.",
            "Age is just a number, cake is forever.",
            "Balloon season has arrived.",
            "Frosted, happy, and one year wiser.",
            "Cheers to another year.",
            "Party mode: on.",
        ],
        "kids": [
            "Q: Why did the birthday cake go to the doctor? A: It was feeling crumby!",
            "Q: What do you call a cake that can sing? A: A birthday Cake-aoke star!",
            "Q: Why did the balloon go to school? A: To get a little more air in its education!",
            "Q: What did one candle say to the other? A: 'Don't birthday-blow this for me!'",
            "Q: Why do we put candles on top of a birthday cake? A: Because it's hard to put them on the bottom!",
            "Q: What do you get when you cross a birthday cake with a vampire? A: A cake that bites back!",
            "Q: Why was the birthday party so loud? A: Because everyone brought their own horns!",
            "Q: What do you say to a birthday cake? A: 'You're so sweet, no crumbs given!'",
            "Q: Why did the present get in trouble? A: It was caught unwrapping secrets!",
            "Q: What's a birthday cake's favorite game? A: Hide and sprinkle!",
        ],
        "love": [
            "You're the candle that lights up every one of my years.",
            "Happy birthday to the icing on the cake of my whole life.",
            "I'd blow out every candle just to wish for more years with you.",
            "You make every birthday feel like the best one yet.",
            "You're sweeter than any cake on your birthday table.",
            "Loving you gets better with every candle we add.",
            "You're my favorite reason to celebrate, birthday or not.",
            "Every year with you is the best gift on the list.",
            "You're the sprinkles on an already sweet life.",
            "Happy birthday to the one I'd pick, cake and all, every year.",
        ],
        "birthday": [
            "Happy birthday — may your cake be sweet and your candles cooperative.",
            "Here's to another year of you being the best part of every party.",
            "Happy birthday to someone who gets better, like cake, with age.",
            "Hope your birthday has more candles than you can actually blow out in one try.",
            "Happy birthday — go eat cake for breakfast, lunch, and dinner.",
            "Another year older, still the sweetest one in the room.",
            "Happy birthday to someone worth celebrating all year, not just today.",
            "May your birthday wish come true before the candles even go out.",
        ],
        "pickup_lines": [
            "Are you my birthday cake? Because I can't stop thinking about you.",
            "Is today your birthday? Because you look like a present I'd love to unwrap.",
            "I must be a candle, because I'm lit up every time I see you.",
            "Are you a birthday wish? Because I'd make you come true.",
            "Did you just blow out a candle, or did my heart just skip?",
            "I'd skip my own cake just to spend your birthday with you.",
            "You must be confetti, because you brighten up every room.",
            "Are you a party? Because things got a lot more fun when you arrived.",
        ],
        "jokes": [
            "Q: Why don't birthdays ever go on diets? A: Because cake is non-negotiable!",
            "Q: What did the balloon say at the birthday party? A: 'I'm about to burst with excitement!'",
            "Q: Why did the cake go to therapy? A: It had too many layers to deal with!",
            "Q: What do you call an old birthday cake? A: A vintage dessert!",
            "Q: Why was the birthday candle so confident? A: It knew it would be the center of attention!",
            "Q: What do you get when you cross a birthday with a comedian? A: A party that's a real blast!",
            "Q: Why did the present break up with the wrapping paper? A: It needed more space!",
            "Q: What's a birthday cake's least favorite day? A: The day after, obviously!",
        ],
        "how_to_use": "Birthday puns work in cards, cake toppers, party banners, group chat messages, and any caption for the candles-and-cake photo that always gets the most likes.",
        "faqs": [
            {
                "q": "What are the best birthday puns?",
                "a": "The best birthday puns use real birthday words — cake, candles, balloons, wishes — instead of generic 'getting older' jokes. Lines like 'cake mode on' and 'candle power' work because they fit directly on a card or cake topper. The strongest ones double as both a joke and a caption.",
            },
            {
                "q": "Are birthday puns good for kids?",
                "a": "Yes, birthday puns are great for kids since birthdays are already one of their favorite topics. Clean Q&A jokes about cake, candles and balloons are easy to understand and perfect for party games or classroom birthday shout-outs.",
            },
            {
                "q": "How do you make a birthday pun?",
                "a": "Start with a birthday-specific word — cake, candle, wish, balloon, frosting — and find a similar-sounding phrase, like 'crumby' from 'crummy.' Our guide on how to write a pun covers the full step-by-step method.",
            },
        ],
        "bridge_links": [
            {"label": "Life Event Puns", "slug": "life-event-puns"},
            {"label": "Puns for Cards", "slug": "puns-for-cards"},
            {"label": "Love Puns", "slug": "love-puns"},
        ],
    },

}
